---
title: "Moderated Multiple Regression - Lab Quiz"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I examined the extent to which exam grades (E) were predicted by anxiety (A) and preparation (P). As indicated in Table 1, when the predictors were examined individually, there was a strong positive relation between anxiety and exam grades, *r* = .69, 95% CI[.64, .73], such that as anxiety increased exam grades increased. In contrast, there was a weak to moderate positive relation between preparation and exam grades, *r* = .23, 95% CI[.15, .31], such that as preparation increased so did exam grades. Further, there was a moderate to strong positive relation between anxiety and preparation, *r* = .49, 95% CI[.42, .56], such that as anxiety increased, so did preparation. 

I used moderated multiple regression to test the extent to which the relation between anxiety and exam grades depended on the amount of exam preparation. I assessed this moderation by examining the interaction between anxiety and preparation using centered predictors (consistent  with the recommendations of Cohen, Cohen, West, and Aiken (2003)), see Table 2. Together the predictors (anxiety, preparation, and their product) accounted for a substantial variance in exam grades, $R^2=.62$, 95% CI[.57, .66], *p* < .01. 

The results for the interaction term in this analysis were significant, but the semi-partial correlation for this term was small. Specifically, the product term for anxiety by preparation revealed a significant relationship, *t*(496)= 6.06, *p* < .0001, which suggests the presence of an interaction. However, the product term's squared semi-partial correlation revealed that the proportion of variance accounted for was small, $sr^2=.03$, 95% CI[.01, .05]. This means that preparation accounted for only an additional 3% of the variance in exam grades beyond anxiety alone. Despite this significant interaction, the amount of variation accounted for by the interaction may not be very meaningful. To further qualify the findings, I opted to explore the regression surface with simple slope analyses, but caution is recommended when reviewing these results. 

The regression surface is presented in Figure 1 and the simple-slope cross-sections are presented in Figure 2. When preparation was high (i.e., +1 SD) there was a positive relationship between anxiety and exam grades, $b=19.49$, 95% CI[17.50, 21.48], t(496)=19.26, *p* < .0001, see Equation 1 below. Similarly, when preparation was low (i.e., -1 SD), there was a positive relation between anxiety and exam grades such that as anxiety increased exam grades also increased, $b=11.02$, 95% CI[9.08, 12.96], t(496)=11.16, *p* < .0001, see Equation 2 below.


$\hat{E}= 19.49A + 55.90$   (1)

$\hat{E}= 11.02A + 42.52$   (2)

In summary, while there was a significant interaction between anxiety and preparation, the amount of additional variance accounted for by this interaction was small. Further, the relationship depicted at low and high preparation was counterintuitive to what was expected. Regardless of whether the students prepared for their exam a lot (1 SD) or little (-1 SD), their exam grades increased with anxiety. Further research is needed to delineate this relationship. 